// <auto-generated />
using System;
using FoodOrder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodOrder.API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210712074755_Add_Delete_Field_For_Entity")]
    partial class Add_Delete_Field_For_Entity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FoodOrder.Core.Models.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AppUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TimeDeleted")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AppUserID");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("TimeDeleted")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AppRole");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9e08f48-883c-42dc-a700-da5cf1d81aa3"),
                            ConcurrencyStamp = "118a9f9d-dc51-49a6-ab0d-3ad0eeca4488",
                            Description = "This is Admintrator role.",
                            IsDeleted = false,
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("74d17d8b-3f91-4d3a-893f-09b4e51e3834"),
                            ConcurrencyStamp = "291213c2-b75c-4c93-ae7a-467383587728",
                            Description = "This is User role.",
                            IsDeleted = false,
                            Name = "user",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = new Guid("1267bf30-8eea-4370-bbcd-12f74e29c656"),
                            ConcurrencyStamp = "235a3125-d734-4655-916e-7c2ddc8f1b2d",
                            Description = "This is Manager role.",
                            IsDeleted = false,
                            Name = "manager",
                            NormalizedName = "MANAGER"
                        });
                });

            modelBuilder.Entity("FoodOrder.Core.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpire")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeCreateJWT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeDeleted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AppUser");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4e253b2-756e-48b8-9c42-b5acb139bed4"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8762c19d-97e0-4fe6-b84c-f5c645952e8f",
                            DateOfBirth = new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jame@gmail.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Jame",
                            NormalizedEmail = "JAME@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEG8dtPLg+U6aUE9yIPco+EPIGYqP/O/e4dLv1PHNjCCnK7vjdrajxLRfNR7zkRQIoA==",
                            PhoneNumber = "+111111111",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpire = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TimeCreateJWT = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("daeb6f0d-eefe-4250-9ecd-28b3243eb684"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c8e22d8f-3315-43b8-99ea-880d1dbfd2e3",
                            DateOfBirth = new DateTime(1990, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "messi10@gmail.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            Name = "Messi",
                            NormalizedEmail = "MESSI10@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIHmT9jZM9GsH/1SakDhajrh/dOxVPLxzzTpxZ24IrTZUW99LCWtpjyfzqvnmrvi5A==",
                            PhoneNumber = "+111111111",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpire = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TimeCreateJWT = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TwoFactorEnabled = false,
                            UserName = "messi10"
                        });
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Cart", b =>
                {
                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("FoodID", "AppUserId");

                    b.HasIndex("AppUserId");

                    b.ToTable("Cart");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            AppUserId = new Guid("daeb6f0d-eefe-4250-9ecd-28b3243eb684"),
                            Quantity = 1
                        },
                        new
                        {
                            FoodID = 2,
                            AppUserId = new Guid("daeb6f0d-eefe-4250-9ecd-28b3243eb684"),
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TimeDeleted")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Com trua cac loai",
                            IsDeleted = false,
                            Name = "Com trua"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Nuoc giai khat cac loai",
                            IsDeleted = false,
                            Name = "Nuoc giai khat"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Mon an kem",
                            IsDeleted = false,
                            Name = "Cac mon an kem mon chinh"
                        });
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Food", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SaleCampaignID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeDeleted")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("SaleCampaignID");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Count = 100,
                            Description = "Com tam lam tu by quyet gia truyen co 2 khong 1",
                            IsDeleted = false,
                            Name = "Com tam gia truyen",
                            Price = 15000.0
                        },
                        new
                        {
                            ID = 2,
                            Count = 57,
                            Description = "Canh rong bien thit bam",
                            IsDeleted = false,
                            Name = "Canh rong bien",
                            Price = 10000.0
                        },
                        new
                        {
                            ID = 3,
                            Count = 1000,
                            Description = "Nuoc giai khat pepsi",
                            IsDeleted = false,
                            Name = "Pepsi",
                            Price = 7000.0
                        },
                        new
                        {
                            ID = 4,
                            Count = 200,
                            Description = "Tra da lam tu by quyet gia truyen co 2 khong 1",
                            IsDeleted = false,
                            Name = "Tra da",
                            Price = 5000.0
                        });
                });

            modelBuilder.Entity("FoodOrder.Core.Models.FoodCategory", b =>
                {
                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("TimeDeleted")
                        .HasColumnType("datetime2");

                    b.HasKey("FoodID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("FoodCategory");

                    b.HasData(
                        new
                        {
                            FoodID = 1,
                            CategoryID = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            FoodID = 3,
                            CategoryID = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            FoodID = 4,
                            CategoryID = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            FoodID = 3,
                            CategoryID = 1,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Notification", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeDeleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("UserReceived")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressName")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressString")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AppUserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("datetime2");

                    b.Property<double>("FinalTotalPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("OrderStatusID")
                        .HasColumnType("int");

                    b.Property<double?>("PromotionAmount")
                        .HasColumnType("float");

                    b.Property<int?>("PromotionID")
                        .HasColumnType("int");

                    b.Property<int?>("SaleCampaignID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeDeleted")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AppUserID");

                    b.HasIndex("OrderStatusID");

                    b.HasIndex("PromotionID");

                    b.HasIndex("SaleCampaignID");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddressName = "Nha",
                            AddressString = "ABC",
                            AppUserID = new Guid("daeb6f0d-eefe-4250-9ecd-28b3243eb684"),
                            CreatedDate = new DateTime(2021, 7, 12, 14, 47, 54, 48, DateTimeKind.Local).AddTicks(2077),
                            FinalTotalPrice = 0.0,
                            IsDeleted = false,
                            IsPaid = false,
                            OrderStatusID = 1,
                            PromotionID = 1
                        });
                });

            modelBuilder.Entity("FoodOrder.Core.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SaleCampaignID")
                        .HasColumnType("int");

                    b.Property<float?>("SalePercent")
                        .HasColumnType("real");

                    b.Property<DateTime?>("TimeDeleted")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderID", "FoodID");

                    b.HasIndex("FoodID");

                    b.HasIndex("SaleCampaignID");

                    b.ToTable("OrderDetail");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            FoodID = 1,
                            Amount = 1,
                            IsDeleted = false,
                            Price = 12000.0
                        },
                        new
                        {
                            OrderID = 1,
                            FoodID = 3,
                            Amount = 2,
                            IsDeleted = false,
                            Price = 5000.0
                        });
                });

            modelBuilder.Entity("FoodOrder.Core.Models.OrderStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("OrderStatus");

                    b.HasData(
                        new
                        {
                            ID = 2,
                            Description = "",
                            Name = "Đang chuẩn bị"
                        },
                        new
                        {
                            ID = 3,
                            Description = "",
                            Name = "Đang giao hàng"
                        },
                        new
                        {
                            ID = 4,
                            Description = "",
                            Name = "Đã nhận hàng"
                        },
                        new
                        {
                            ID = 5,
                            Description = "",
                            Name = "Đã hủy"
                        });
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Promotion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Desciption")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("EndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 7, 12, 14, 47, 53, 997, DateTimeKind.Local).AddTicks(7324));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("default.png");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("bit");

                    b.Property<double>("Max")
                        .HasColumnType("float");

                    b.Property<double>("MinPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Percent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(10f);

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 7, 12, 14, 47, 53, 996, DateTimeKind.Local).AddTicks(2564));

                    b.Property<DateTime?>("TimeDeleted")
                        .HasColumnType("datetime2");

                    b.Property<int>("UseTimes")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Promotion");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Code = "THANHVIENMOI",
                            Enabled = true,
                            EndDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            IsGlobal = false,
                            Max = 5000.0,
                            MinPrice = 50000.0,
                            Name = "Chao thanh vien moi",
                            Percent = 0.25f,
                            Priority = 0,
                            StartDate = new DateTime(2021, 7, 12, 14, 47, 54, 50, DateTimeKind.Local).AddTicks(46),
                            UseTimes = 100
                        });
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Rating", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Star")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<DateTime>("TimeCreate")
                        .IsUnicode(true)
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeDeleted")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderID", "FoodID");

                    b.HasIndex("AppUserId");

                    b.HasIndex("FoodID");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.SaleCampaign", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desciption")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Percent")
                        .HasColumnType("real");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeDeleted")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("SaleCampaign");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.SaleCampaignFood", b =>
                {
                    b.Property<int>("FoodID")
                        .HasColumnType("int");

                    b.Property<int>("SaleCampaignID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("TimeDeleted")
                        .HasColumnType("datetime2");

                    b.HasKey("FoodID", "SaleCampaignID");

                    b.HasIndex("SaleCampaignID");

                    b.ToTable("SaleCampaignFood");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AppRoleClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AppUserClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AppUserRole");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("b4e253b2-756e-48b8-9c42-b5acb139bed4"),
                            RoleId = new Guid("b9e08f48-883c-42dc-a700-da5cf1d81aa3")
                        },
                        new
                        {
                            UserId = new Guid("daeb6f0d-eefe-4250-9ecd-28b3243eb684"),
                            RoleId = new Guid("1267bf30-8eea-4370-bbcd-12f74e29c656")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserToken");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Address", b =>
                {
                    b.HasOne("FoodOrder.Core.Models.AppUser", "AppUser")
                        .WithMany("Addresses")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Cart", b =>
                {
                    b.HasOne("FoodOrder.Core.Models.AppUser", "AppUser")
                        .WithMany("Carts")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrder.Core.Models.Food", "Food")
                        .WithMany("Carts")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Food", b =>
                {
                    b.HasOne("FoodOrder.Core.Models.SaleCampaign", null)
                        .WithMany("SaleCampaignFoods")
                        .HasForeignKey("SaleCampaignID");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.FoodCategory", b =>
                {
                    b.HasOne("FoodOrder.Core.Models.Category", "Category")
                        .WithMany("FoodCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrder.Core.Models.Food", "Food")
                        .WithMany("FoodCategories")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Notification", b =>
                {
                    b.HasOne("FoodOrder.Core.Models.AppUser", "AppUser")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Order", b =>
                {
                    b.HasOne("FoodOrder.Core.Models.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrder.Core.Models.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrder.Core.Models.Promotion", "Promotion")
                        .WithMany("Orders")
                        .HasForeignKey("PromotionID");

                    b.HasOne("FoodOrder.Core.Models.SaleCampaign", null)
                        .WithMany("Orders")
                        .HasForeignKey("SaleCampaignID");

                    b.Navigation("AppUser");

                    b.Navigation("OrderStatus");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.OrderDetail", b =>
                {
                    b.HasOne("FoodOrder.Core.Models.Food", "Food")
                        .WithMany("OrderDetails")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrder.Core.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrder.Core.Models.SaleCampaign", "SaleCampaign")
                        .WithMany()
                        .HasForeignKey("SaleCampaignID");

                    b.Navigation("Food");

                    b.Navigation("Order");

                    b.Navigation("SaleCampaign");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Rating", b =>
                {
                    b.HasOne("FoodOrder.Core.Models.AppUser", "AppUser")
                        .WithMany("Ratings")
                        .HasForeignKey("AppUserId");

                    b.HasOne("FoodOrder.Core.Models.Food", "Food")
                        .WithMany("Ratings")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrder.Core.Models.Order", "Order")
                        .WithMany("Ratings")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Food");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.SaleCampaignFood", b =>
                {
                    b.HasOne("FoodOrder.Core.Models.Food", "Food")
                        .WithMany("SaleCampaignFoods")
                        .HasForeignKey("FoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrder.Core.Models.SaleCampaign", "SaleCampaign")
                        .WithMany()
                        .HasForeignKey("SaleCampaignID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("SaleCampaign");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("FoodOrder.Core.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FoodOrder.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FoodOrder.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("FoodOrder.Core.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrder.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FoodOrder.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodOrder.Core.Models.AppUser", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Carts");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Category", b =>
                {
                    b.Navigation("FoodCategories");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Food", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("FoodCategories");

                    b.Navigation("OrderDetails");

                    b.Navigation("Ratings");

                    b.Navigation("SaleCampaignFoods");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.Promotion", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrder.Core.Models.SaleCampaign", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("SaleCampaignFoods");
                });
#pragma warning restore 612, 618
        }
    }
}
